name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          static_site_generator: next
      - name: Install dependencies
        run: npm ci
      - name: Debug Next.js version
        run: npx next --version
      - name: Build with Next.js
        run: |
          echo "Building Next.js application..."
          npm run build
          echo "Build completed. Checking output directory..."
          ls -la
          if [ -d ".next" ]; then
            echo ".next directory exists."
            ls -la .next/
            if [ -d "out" ]; then
              echo "'out' directory exists."
              ls -la out/
            else
              echo "'out' directory does not exist. Copying from .next"
              mkdir -p out
              if [ -f ".next/server/pages/index.html" ]; then
                cp -r .next/server/pages/* out/
              else
                echo "No static HTML files found. Creating placeholder index.html"
                echo "<html><body><h1>Build Error</h1><p>No static pages were generated. Check GitHub Actions logs.</p></body></html>" > out/index.html
              fi
            fi
          else
            echo "Warning: '.next' directory does not exist. Creating placeholder..."
            mkdir -p out
            echo "<html><body><h1>Build Error</h1><p>Next.js build failed. Check GitHub Actions logs for details.</p></body></html>" > out/index.html
          fi
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out
          name: github-pages-build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages-build
