name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          static_site_generator: next
      - name: Install dependencies
        run: npm ci
      - name: Debug environment
        run: |
          echo "Node version:"
          node --version
          echo "NPM version:"
          npm --version
          echo "Next.js version:"
          npx next --version
          echo "Workspace contents:"
          ls -la
      - name: Build with Next.js
        run: |
          rm -rf .next out
          npm run build
          echo "Build output:"
          ls -la
          if [ -d "out" ]; then
            echo "out directory exists with content:"
            ls -la out/
            if [ -f "out/index.html" ]; then
              echo "index.html found!"
            else
              echo "index.html NOT found!"
            fi
          else
            echo "ERROR: 'out' directory not found!"
          fi
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out
          name: github-pages-build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages-build
